twig:
  default_path: "%kernel.project_dir%/templates"

  globals:
    front:  "Vous êtes sur la partie front"
    admin:  "Vous êtes sur la partie admin"
    geditors: '@App\Globals\Editors'
    glicences: '@App\Globals\Licences'

when@test:
  twig:
    strict_variables: true